version : 0.1

 phases:
   build:
     commands:
       - echo Nothing to do yet
 artifacts:
   files:
     - index.html
     - favicon.ico
     - Ayo Sal_CV.pdf
     - styles/main.css
     - images/*
